### ISSUE TITLE
compile error with php 5.5 and 5.6...

### ISSUE THREAD

**Issue by mcarbonneaux** [ppadron/php-augeas#1]
when compile with php 5.5 or 5.6 they comply with this error:

```
/php-augeas/augeas.c: In function ‘zm_startup_augeas’:
/php-augeas/augeas.c:173: error: expected expression before ‘void’
/php-augeas/augeas.c: In function ‘zim_Augeas___construct’:
/php-augeas/augeas.c:230: error: expected expression before ‘void’
/php-augeas/augeas.c:234: error: expected expression before ‘void’
```

**Comment by mcarbonneaux** [comment]
fix in https://github.com/ppadron/php-augeas/pull/4 pull request.
